USE do_everyday_prod;
create table board (id bigint not null auto_increment, color_hex varchar(255) not null, name varchar(255), app_user_id varchar(255), primary key (id)) engine=InnoDB;
create table budget (id bigint not null auto_increment, description varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table task (id bigint not null auto_increment, create_date datetime, description varchar(255), name varchar(255), photo longblob, board_id bigint, primary key (id)) engine=InnoDB;
create table task_manager (id bigint not null auto_increment, is_done bit, priority varchar(255), task_id bigint, primary key (id)) engine=InnoDB;
create table task_member (id bigint not null auto_increment, app_user_id varchar(255), primary key (id)) engine=InnoDB;
create table task_member_task_manager (task_manager_id bigint not null, task_member_id bigint not null) engine=InnoDB;
create table transaction (id bigint not null auto_increment, currency varchar(255), date datetime not null, description varchar(255), value double precision not null, budget_id bigint, primary key (id)) engine=InnoDB;
create table user (id varchar(255) not null, account_non_expired bit default 1 not null, account_non_locked bit default 1 not null, credentials_non_expired bit default 1 not null, email varchar(255), enabled bit default true not null, password varchar(255) not null, photo longblob, role varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_weather_properties (id varchar(255) not null, language integer, latitude double precision, longitude double precision, units integer, user_id varchar(255), primary key (id)) engine=InnoDB;
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table board add constraint FK13s67jmrjuu7xndjskctj3ypj foreign key (app_user_id) references user (id);
alter table task add constraint FKrar3pm9ixqub1nilws0l8l22w foreign key (board_id) references board (id);
alter table task_manager add constraint FK82wv11lkj1657fmwr6ky4jol2 foreign key (task_id) references task (id);
alter table task_member add constraint FKkpa2jq9lfi5qpcn8yln48ctgf foreign key (app_user_id) references user (id);
alter table task_member_task_manager add constraint FK739i1i80a7jixtrempe0ka2y4 foreign key (task_member_id) references task_manager (id);
alter table task_member_task_manager add constraint FKj8qos3agvghc0s02v8pkyfqma foreign key (task_manager_id) references task_member (id);
alter table transaction add constraint FK7ul8m5q12we515aa7b7ao0p44 foreign key (budget_id) references budget (id);
alter table user_weather_properties add constraint FK5xfo16auh0gpa95j99rw6ox0q foreign key (user_id) references user (id);
